name: Cloudflare Pages Publish

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Cloudlfare pages
    permissions:
      contents: read
      deployments: write
    
    name: Publish job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Publish
        uses: cloudflare/pages-action@1.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: ${{ secrets.PROJECT_NAME }}
          directory: ${{ secrets.ASSET_DIRECTORY }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
